# xenial (16.04) is so outdated that it has trouble with LTO.
# bionic (18.04) is good, but doesn't have the package librlottie-dev
# focal (20.04) isn't officially supported by Travis yet,
#   but I expect that it will be supported at least until 2026.
dist: focal
language: cpp
compiler:
  - gcc
  - clang
env:
# Try to be nice to the builder
  - CMAKE_FLAGS="                                                 " INSTALL_LOCAL_LOTTIE=n
  - CMAKE_FLAGS="-DNoWebp=1                                       " INSTALL_LOCAL_LOTTIE=n
  - CMAKE_FLAGS="           -DNoTranslations=1                    " INSTALL_LOCAL_LOTTIE=n
#  - CMAKE_FLAGS="-DNoWebp=1 -DNoTranslations=1                    " INSTALL_LOCAL_LOTTIE=n
  - CMAKE_FLAGS="                              -DNoLottie=1       " INSTALL_LOCAL_LOTTIE=n
#  - CMAKE_FLAGS="-DNoWebp=1                    -DNoLottie=1       " INSTALL_LOCAL_LOTTIE=n
#  - CMAKE_FLAGS="           -DNoTranslations=1 -DNoLottie=1       " INSTALL_LOCAL_LOTTIE=n
#  - CMAKE_FLAGS="-DNoWebp=1 -DNoTranslations=1 -DNoLottie=1       " INSTALL_LOCAL_LOTTIE=n
  - CMAKE_FLAGS="                              -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
#  - CMAKE_FLAGS="-DNoWebp=1                    -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
#  - CMAKE_FLAGS="           -DNoTranslations=1 -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
  - CMAKE_FLAGS="-DNoWebp=1 -DNoTranslations=1 -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
matrix:
# Be even nicer by excluding half of the combinations:
  exclude:
#    - compiler: gcc
#      env: CMAKE_FLAGS="                                                 " INSTALL_LOCAL_LOTTIE=n
    - compiler: clang
      env: CMAKE_FLAGS="                                                 " INSTALL_LOCAL_LOTTIE=n
    - compiler: gcc
      env: CMAKE_FLAGS="-DNoWebp=1                                       " INSTALL_LOCAL_LOTTIE=n
#    - compiler: clang
#      env: CMAKE_FLAGS="-DNoWebp=1                                       " INSTALL_LOCAL_LOTTIE=n
#    - compiler: gcc
#      env: CMAKE_FLAGS="           -DNoTranslations=1                    " INSTALL_LOCAL_LOTTIE=n
    - compiler: clang
      env: CMAKE_FLAGS="           -DNoTranslations=1                    " INSTALL_LOCAL_LOTTIE=n
    - compiler: gcc
      env: CMAKE_FLAGS="                              -DNoLottie=1       " INSTALL_LOCAL_LOTTIE=n
#    - compiler: clang
#      env: CMAKE_FLAGS="                              -DNoLottie=1       " INSTALL_LOCAL_LOTTIE=n
#    - compiler: gcc
#      env: CMAKE_FLAGS="                              -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
    - compiler: clang
      env: CMAKE_FLAGS="                              -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
    - compiler: gcc
      env: CMAKE_FLAGS="-DNoWebp=1 -DNoTranslations=1 -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y
#    - compiler: clang
#      env: CMAKE_FLAGS="-DNoWebp=1 -DNoTranslations=1 -DNoBundledLottie=1" INSTALL_LOCAL_LOTTIE=y

cache:
  directories:
  - .travis_cache/

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gperf libpurple-dev libwebp-dev libgtest-dev
  # TODO: php is not strictly necessary (I don't have php installed), but it apparently is on Travis?!
  # Ubbuntu Bionic (php on image): works
  #     https://travis-ci.com/github/BenWiederhake/tdlib-purple/jobs/358165125#L1186
  # Ubuntu Focal (no php on image): fails
  #     https://travis-ci.com/github/BenWiederhake/tdlib-purple/builds/174538475#L799
  # Ubuntu Focal, manually install php: works
  #     https://travis-ci.com/github/BenWiederhake/tdlib-purple/builds/174539831#L907
  - sudo apt-get install -y -qq php
  - if [ "x${INSTALL_LOCAL_LOTTIE}" = "xy" ] ; then sudo apt-get install -y -qq librlottie-dev ; fi

script:
  - ./travis_build_td.sh
  - cd build
# TODO: Try out building with the voip library?
# libpurple uses the deprecated glib-type `GParameter` and the deprecated glib-macro `G_CONST_RETURN`, which
# spams the console with useless warnings that we can do nothing about.
  - cmake -DCMAKE_CXX_FLAGS=-DGLIB_DISABLE_DEPRECATION_WARNINGS -DTd_DIR=.travis_cache/td_destdir/usr/local/lib/cmake/Td -DNoVoip=1 ..
  - make -j2 VERBOSE=1
  - make -j2 tests
  - make run-tests
  - make install DESTDIR=tdprpl_destdir install
